[preferred]
# [...](asc_slot://start-slot-7)屏幕共享和截图使用 wlr 后端
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr

# [...](asc_slot://start-slot-9)其他功能（如文件选择器、设置等）推荐使用 GTK 后端
# 因为 wlr 后端只有截图录屏功能，没有文件选择器
default=kde

